package net.hypixel.api.util.pets;


public enum PetType {

    CAT_BLACK, CAT_RED, CAT_SIAMESE,
    CAT_BLACK_BABY, CAT_RED_BABY, CAT_SIAMESE_BABY,
    WILD_OCELOT, WILD_OCELOT_BABY,

    PIG, PIG_BABY, PIG_ZOMBIE, PIG_ZOMBIE_BABY,
    COW, COW_BABY, MOOSHROOM, MOOSHROOM_BABY,
    WOLF, WOLF_BABY,
    CHICKEN, CHICKEN_BABY,

    HORSE_BROWN, HORSE_WHITE, HORSE_BLACK, HORSE_UNDEAD, HORSE_CREAMY, HORSE_CHESTNUT, HORSE_DARK_BROWN, HORSE_GREY, DONKEY, MULE, HORSE_SKELETON,
    HORSE_CREAMY_BABY, HORSE_CHESTNUT_BABY, HORSE_DARK_BROWN_BABY, HORSE_GRAY_BABY, BROWN_HORSE_BABY,

    VILLAGER_FARMER, VILLAGER_LIBRARIAN, VILLAGER_PRIEST, VILLAGER_BLACKSMITH, VILLAGER_BUTCHER, ZOMBIE_VILLAGER, WITCH,
    VILLAGER_FARMER_BABY, VILLAGER_LIBRARIAN_BABY, VILLAGER_PRIEST_BABY, VILLAGER_BLACKSMITH_BABY, VILLAGER_BUTCHER_BABY,

    SHEEP_WHITE, SHEEP_GRAY, SHEEP_BROWN, SHEEP_SILVER, SHEEP_BLACK, SHEEP_PINK, SHEEP_ORANGE, SHEEP_MAGENTA, SHEEP_LIGHT_BLUE, SHEEP_YELLOW, SHEEP_LIME,
    SHEEP_CYAN, SHEEP_PURPLE, SHEEP_BLUE, SHEEP_GREEN, SHEEP_RED,
    SHEEP_ORANGE_BABY, SHEEP_MAGENTA_BABY, SHEEP_LIGHT_BLUE_BABY, SHEEP_YELLOW_BABY, SHEEP_LIME_BABY, SHEEP_CYAN_BABY, SHEEP_PURPLE_BABY, SHEEP_BLUE_BABY,
    SHEEP_GREEN_BABY, SHEEP_RED_BABY, SHEEP_RAINBOW, SHEEP_PINK_BABY, SHEEP_WHITE_BABY, SHEEP_GRAY_BABY, SHEEP_BROWN_BABY, SHEEP_SILVER_BABY, SHEEP_BLACK_BABY,

    BROWN_RABBIT, WHITE_RABBIT, BLACK_RABBIT, BLACK_WHITE_RABBIT, GOLD_RABBIT, SALT_PEPPER_RABBIT,

    SILVERFISH, ENDERMITE,
    ZOMBIE, ZOMBIE_BABY,
    SPIDER, CAVE_SPIDER,
    SKELETON, WITHER_SKELETON,

    SLIME_BIG, SLIME_SMALL, SLIME_TINY, MAGMA_CUBE_BIG, MAGMA_CUBE_SMALL, MAGMA_CUBE_TINY,

    CREEPER, CREEPER_POWERED,

    SNOWMAN, GREEN_HELPER, RED_HELPER,

    IRON_GOLEM,
    ENDERMAN,
    BLAZE,
    BAT,
    SQUID,
    HEROBRINE;

    public static final PetType[] VALUES = values();

}
